import { Geist, Geist_Mono } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import Swiper from 'swiper';
import FloatingCart from "./FloatingCart";
// import Swiper styles
import 'swiper/css';


import "./globals.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css"; // Import the Font Awesome CSS


config.autoAddCss = false; // Tell Font Awesome to skip adding the CSS automatically

import Navbar from "./_Navbar/Navbar"
import Footer from "../Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Navbar/>
        {children}
        <FloatingCart />
        <Footer/>
      </body>
    </html>
  );
}
